matriz.normal = matrix(rnorm(3*5, 10, 3.6), nrow=3)
colnames(matriz.normal) = paste("C", 1:5, sep="")
rownames(matriz.normal) = paste("L", 1:3, sep="")
media.linha = rowMeans(matriz.normal)
var.linha = apply(matriz.normal, 1, var)
linha = data.frame (media=media.linha, var=var.linha)
media.coluna = colMeans(matriz.normal)
var.coluna = apply(matriz.normal, 2, var)
coluna = data.frame (media=media.coluna, var=var.coluna)
