conj1 = rnorm(10, 6, 3)
conj2 = rnorm(10, 7.5, 3.2)
source("simula.r")
sim.dif = simula(conj2, conj1, teste="bi")
sim.maior = simula(conj2, conj1, teste="uni")
t.dif = t.test(conj1, conj2)
t.maior = t.test(conj1, conj2, alternative="less")
