obj1.folhas = rnorm(10000, 9.5, 2.2)
obj1.valores = sample(obj1.folhas, 1000, replace = TRUE)
obj2.matriz = matrix(obj1.valores, ncol = 10)
dimnames(obj2.matriz) = list(paste0("individuo", 1:100), paste0("folha", 1:10))
especies = sample(paste0("especie", 1:5), 100, replace = TRUE)
media.individuo = rowMeans(obj2.matriz)
media.especie =  tapply(media.individuo, especies, mean)
medias = list( "porIndividuo" = media.individuo, "porEspecie" = media.especie)
obj3.dataframe = data.frame(obj2.matriz,especies)
objultimo = list(obj1.valores, obj2.matriz, obj3.dataframe, medias)
names(objultimo) = c("obj1.valores", "obj2.matriz", "obj3.dataframe", "medias")
